version: 0.0

os: linux

files:
  - source: app
    destination: /app
  - source: codedeply/app.service
    destination: /etc/systemd/system/
file_exists_behavior: OVERWRITE

hooks:
  ApplicationStart:
    - location: codedeply/start.sh
      timeout: 180
      runas: root