version: '3.1'

volumes:
  node_modules:

services:

  echo:
    image: golang:1.21-alpine
    tty: true
    volumes: 
      - ./src:/app

  next:
    image: node:18-alpine
    tty: true
    volumes:
      - ./src:/app
  
  nginx:
    image: nginx:1.21-alpine
    depends_on:
      - next
      - echo
    volumes:
      - ./dev/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
