version: '3.1'

volumes:
  node_modules:

services:

  echo:
    image: golang:1.21-alpine
    tty: true
    volumes: 
      - ./src/echo:/app
    working_dir: /app

  next:
    image: node:18-alpine
    tty: true
    volumes:
      - ./src/next:/app
    working_dir: /app
  
  nginx:
    image: nginx:1.21-alpine
    depends_on:
      - next
      - echo
    volumes:
      - ./dev/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
  
  terraform:
    image: hashicorp/terraform:1.5.6
    tty: true
    volumes:
      - ./infra/terraform:/app
    working_dir: /app
    entrypoint: sh
    environment:
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - TF_VAR_assume_role_arn=${AWS_ROLE_ARN}

