version: 0.0

os: linux

files:
  - source: /
    destination: /app
  - source: codedeploy/app.service
    destination: /etc/systemd/system/

file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 775
    type:
      - file
      - directory

hooks:
  ApplicationStart:
    - location: codedeploy/start.sh
      timeout: 180
      runas: ec2-user
