name: deploy_next

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'src/next/**'

jobs:
  deploy:
    concurrency:
      group: ${{ github.workflow }}

    runs-on: ubuntu-latest

    environment: ${{ github.ref == 'main' && 'stg' || 'stg' }}

    defaults:
      run:
        working-directory: src/gin

    steps:
      - uses: actions/checkout@v4

      - name: Set env
        env:
          TZ: 'Asia/Tokyo'
        run: |
          echo "ARTIFACT_NAME=artifact-$(date +'%Y-%m-%d_%H-%M-%S')-${{ github.sha }}.zip" >> $GITHUB_ENV
      
      - name: Make env
        run: echo "${{ secrets.NEXT_ENV }} > .env.production"
      
      # build next standalone mode
      
      - name: zip artifact
        run: >
          zip -r
          ${{ env.ARTIFACT_NAME }}
          .
          -x node_modules/\* .next\*

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-region: ap-northeast-1
      
      - name: Upload to S3
        run: >
          aws s3 cp
          ${{ env.ARTIFACT_NAME }}
          s3://${{ secrets.NEXT_ARTIFACT_BUCKET }}
      
      - name: Deploy
        run: >
          aws deploy create-deployment
          --application-name next_server
          --deployment-group-name next_server_deployment_group
          --s3-location bucket=${{ secrets.NEXT_ARTIFACT_BUCKET }},bundleType=zip,key=${{ env.ARTIFACT_NAME }}
  